### PR TITLE
no jquery searches

### PR DESCRIPTION
**Pull request by apotropaic**
I didn't have time to write the code for a dropdown, but here is a working js for the input field. I saw the need on issue #2

### CODE REVIEW

**Comment by jimblue** [comment]
Amazing 👍  thank you @apotropaic 
Can't wait for the merge!

**Comment by w00fz** [comment]
FYI i'm looking at this today. There are a few issues with this implementation that i noticed and that i want to fix.
I also want to add support for the live URI querystring when in the /search page and as you type in the field.
I will be using @apotropaic's PR as feature to push my changes.

**Comment by w00fz** [comment]
Got the initial rework in:
 * https://github.com/trilbymedia/grav-plugin-tntsearch/pull/12/files#diff-3c56f1dfc265d93d754c52ea6397c36a
 * https://github.com/trilbymedia/grav-plugin-tntsearch/pull/12/files#diff-1784aeec40c934a63010a661c2001055

Pretty much as you had it already @apotropaic, just restructured and hooked up webpack. Also fixed a few issues as well:

1. support for multiple search/dropdowns per page
2. close the dropdown when clicking in the body (outside the dropdown)
3. fixed the minimum count that was hardcoded to 3 rather than ready from the options
4. have implemented a smarter timer for the keyup which uses lodash throttle

I still need to implement the live URI update on the search page so this PR is still not quite done yet.

Cheers

**Comment by apotropaic** [comment]
Looks awesome! I was going for a no import solution, but makes sense if you are going to use webpack to just pull in the tools you need, like domready and lodash. 

One thought I just had was about using fetch, would it be worth it to include a polyfill for that? I'm sure its got something like 80% coverage, but just a thought. 

And when this is merged, we need to update the learn.getgrav.org website asap! I hit enter almost every time I do an advanced search on that site haha

**Comment by w00fz** [comment]
I’m already using GitHub’s fetch as polyfill and handling it via webpack:
https://github.com/trilbymedia/grav-plugin-tntsearch/pull/12/files#diff-7b9b27bb161c35ae42546d7641ee72b4R20

Should be enough for backward compatibility.

Also yes as soon as I’m done with the missing bit I’ll test the learn and make sure we get that updated as well 😄

**Comment by w00fz** [comment]
History has been now implemented. I'm going to be finally merging this PR on monday.
If you want to give it a spin go ahead!

**Comment by w00fz** [comment]
Merged, thank you so much for your help with this @apotropaic 👍

**Pull request merged**
